//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PJ3ShopThoiTrang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public SanPham()
        {
            this.ChiTietHoaDons = new HashSet<ChiTietHoaDon>();
        }
    
        public int IDSanPham { get; set; }
        public Nullable<int> IDLoaiSanPham { get; set; }
        public Nullable<int> IDSize { get; set; }
        public string TenSanPham { get; set; }
        public string ThuongHieu { get; set; }
        public Nullable<int> GiaMua { get; set; }
        public Nullable<int> GiaBan { get; set; }
        public string MauSac { get; set; }
        public string KieuDang { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public string Anh { get; set; }
        public string MoTa { get; set; }
    
        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
        public virtual SanPham_Size SanPham_Size { get; set; }
    }
}
